name: camera_platform_interface2
description: A common platform interface for the camera plugin.
repository: https://github.com/aramikg/flutter-camera/tree/main/packages/camera/camera_platform_interface
issue_tracker: https://github.com/aramikg/flutter-camera/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.6.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  cross_file: ^0.3.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter

topics:
  - camera
